site_name: Flash Library

nav:
  - General:
    - index.md
  - Info:
    - info/swf.md
    - info/bundle.md
  - Tools:
    - tools/ffdec.md
    - tools/swf2exe.md
    - tools/swf-unbundler.md
  - Players:
    - players/projector.md
    - players/flashpoint.md
    - players/ruffle.md
    - players/waflash.md
  - Games:
    - Super Mario 63:
      - About: games/sm63/sm63.md
      - games/sm63/tas63.md
    - Super Mario Flash (external link): https://rayyaw.github.io/speedrun/resources/#super-mario-flash

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - actionscript

markdown_extensions:
    - markdown.extensions.admonition
