site_name: Flash Library

nav:
  - General:
    - index.md
  - Tools:
    - tools/ffdec.md
  - Players:
    - players/ruffle.md
    - players/waflash.md
  - Games:
    - Super Mario 63:
      - About: games/sm63/sm63.md
      - games/sm63/tas63.md

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - actionscript